language: go
install:
- go get github.com/mitchellh/gox
- go get github.com/aktau/github-release
notifications:
  email: false
after_success:
- "scripts/build_archives.sh"
- "scripts/push_nightly.sh"
deploy:
  provider: releases
  api_key:
    secure: oGwid2rEKM8DShqleWkdal5ASc5SpPYctbwoawyvyGkjjC/zXtfpu30jHcJShthfDbqbOolgCKi+aE7QRwiq0I1ehsyau/Q4UYnko11bE8FYm2CJ0glIAPo4o1LdBUwZvd3C8E/tMcp+CqHOnDnBqLSizqVK/QkXYIOe7LYaqoSWGZbAYJJotvQdZcXXcipjZ/5EWu5pAMX+Z7BjI/Jbs3VH7VIyfl3mqe/tNNhZqzTjmy91r1oblqcizJkG6/1kIo3VYnGbX40oQZERQWpDVV2fElrI9DoPKnkee/c/mmmqsjG2Xh6hEkEskRofQ3/LOI/oY8LOV47zCo6FFX37aGlNfatGxMeD8Wk6NUIOJAmCCjSqEXO4S4A8xz62W+c11ePhR9BU9vohJNnWmYEMlTnjFlmfuCncIBp6h84QC0yhVb7kh5ue1bg5UwamZ5aMZpSS7gqhXUyccZEDqph7VrZQjdvNT8bdUMrWdB+qe6OZStJCUNq/bBaMwYqkrwzQPpDYaH83XHnuKc5tIVo3h+6bD2k5q+rbeGjg0QSEuqp3wgEK36wcmuTE9eQPMvIjONj8tQCgvr3YF82jNDim8mw/yUOF/GRqsmGw7a7dk2t77Vj/OdlCPOf2l4zRJG9ykMwMHqC2o9uT9ZfzfIdqYD64kqTKcq1tKshkZwmkcS0=
  file:
  - bench_darwin_386.tar.gz
  - bench_darwin_amd64.tar.gz
  - bench_freebsd_386.tar.gz
  - bench_freebsd_amd64.tar.gz
  - bench_freebsd_arm.tar.gz
  - bench_linux_386.tar.gz
  - bench_linux_amd64.tar.gz
  - bench_linux_arm.tar.gz
  - bench_netbsd_386.tar.gz
  - bench_netbsd_amd64.tar.gz
  - bench_netbsd_arm.tar.gz
  - bench_openbsd_386.tar.gz
  - bench_openbsd_amd64.tar.gz
  - bench_windows_386.exe.tar.gz
  - bench_windows_amd64.exe.tar.gz
  skip_cleanup: true
  on:
    tags: true
    branch: release
env:
  global:
    secure: HXbH8onw4fcx/qlLPBF5TlxI7kPb/koJ23DAS++8lggwaRjaaVdMQCzlWI6YQr34LcLM1D0ZU/E6VBHV54rW6XNLz1MtnSVQ8NhJ24lwLNsp9gcEPydciCmCPpLJooUjy6Fr98EKdGjOuogsoL7YHvq0RfwiqeNMrrlLa+lkx022TP6RE1WS4GzR2w6iBp3NVUU7iiogO73jZgSz1fxQfPTz4/HbPSeNteFCdIhxpb0/qiVtexohLKYMd/TYnHhp+zbGkuTsIHaTt2d9OGH8YR/VllLtCc3w5ai1DlDCJkazoHLaNhGKUJhg58F1knaih/sbD0EOkBpStg6OsnxsZjNjB7gJRidcDoZlSCVNEZvUWRM8gLUZRPGCnhdXKZJGXgBlkYNtO6hCzchjB6B/3c1iNdhoY7BdSPhQ+I5kcQHsPkKUMI6x1PvkNCWDsaLt6vSjNPGjHt60Yvzgm/ewjy43qk3U0GuFbJY1seVgMT+wjAweuQu/7nA4F72x5/K8loAK53IPErANHb0vhwNdmW/s+Irm2tpKglgcKpW5IDGao9am7tQLpUGsJvHD0qlFW8j6xrSmSbRlhwNM78zOKFtLCTtrWJuoeYkWfSr+ENGm2rOEy2n3Ee4EZqY5dV3uBFcFeEcBuSM6m9qql/3/w7tawh2jZSBL9XHfR4x9/NU=
